apiVersion: v1
kind: Service
metadata:
  annotations: {}

  labels:
    io.kompose.service: lisa-backend
  name: lisa-backend
spec:
  type: NodePort
  ports:
    - name: "80"
      port: 80
      targetPort: 3000
  selector:
    io.kompose.service: lisa-backend
