apiVersion: v1
kind: Service
metadata:
  annotations: {}

  labels:
    io.kompose.service: $(TENANT)-backend
  name: $(TENANT)-backend
spec:
  type: NodePort
  ports:
    - name: "80"
      port: 80
      targetPort: 3000
  selector:
    io.kompose.service: $(TENANT)-backend
