apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  name: $(TENANT)-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: $(TENANT)
  template:
    metadata:
      annotations: {}
      labels:
        io.kompose.service: $(TENANT)
    spec:
      serviceAccountName: $(TENANT)-sa
      containers:
        - envFrom:
               - configMapRef:
                   name: $(TENANT)-configs
               - secretRef:
                   name: $(TENANT)-secrets
          livenessProbe:
           httpGet:
             port: 3000
             path: /
           failureThreshold: 5
           periodSeconds: 30
           timeoutSeconds: 20
          readinessProbe:
            httpGet:
              port: 3000
              path: /
            failureThreshold: 5
            periodSeconds: 30
            timeoutSeconds: 20
          name: $(TENANT)
          image: lisa-image:template
          resources:
            limits:
              memory: "2Gi"
            requests:
              cpu: "0.25"
              memory: "256Mi"
              ephemeral-storage: "2Gi"
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
