apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  name: lisa-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: lisa
  template:
    metadata:
      annotations: {}
      labels:
        io.kompose.service: lisa
    spec:
      serviceAccountName: lisa-sa
      containers:
        - envFrom:
               - configMapRef:
                   name: lisa-configs
               - secretRef:
                   name: lisa-secrets


#        - env:
#            - name: COGNITO_DOMAIN
#              value: eu-west-224focjndv.auth.eu-west-2.amazoncognito.com
#            - name: COGNITO_USER_POOL_ID
#              value: eu-west-2_24fOCjndV
#            - name: COGNITO_CLIENT_ID
#              value: 3dss5tt42f0s7v6tdch6bqg63j
#            - name: COGNITO_CLIENT_SECRET
#              value: 17orb2f19hu0ih6328bhn50jaqrmkg41btpeokbhet9pins6nhln

          image: lisa-image
          livenessProbe:
           httpGet:
             port: 3000
             path: /
           failureThreshold: 5
           periodSeconds: 30
           timeoutSeconds: 10
          name: lisa
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
