apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  name: lisa-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: lisa
  template:
    metadata:
      annotations: {}
      labels:
        io.kompose.service: lisa
    spec:
      serviceAccountName: lisa-sa
      containers:
        - envFrom:
               - configMapRef:
                   name: lisa-configs
               - secretRef:
                   name: lisa-secrets

          image: lisa-image
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            failureThreshold: 5
            periodSeconds: 30
            timeoutSeconds: 20
          readinessProbe:
              httpGet:
                path: /
                port: 3000
              failureThreshold: 5
              periodSeconds: 30
              timeoutSeconds: 20
          name: lisa
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
