resources:
  - service-account.yaml
  - deployment.yaml
  - service.yaml
  - istio/preauthentication.yaml
  - istio/gateway.yaml
  - istio/virtualService.yaml


labels:
  - pairs:
      app: $(TENANT)
      env: ENV_PLACEHOLDER
      app.kubernetes.io/name: $(TENANT)


