resources:
  - ../../base

namespace: lisa


configMapGenerator:
  - name: lisa-configs
    envs:
      - params.env


patches:
  - path: patches/virtualService.yaml
    target:
      kind: VirtualService
  - path: patches/service-account.yaml
    target:
      kind: ServiceAccount
      name: lisa-sa
  - path: patches/allow-ingress.yaml
    target:
      kind: AuthorizationPolicy

labels:
  - pairs:
      env: dev

images:
  - name: lisa-backend-image
    newName: 503561419905.dkr.ecr.eu-west-2.amazonaws.com/lisa/api
    newTag: '1739959086'


