version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    groups:
      actions-updates:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/common"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    groups:
      js-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    groups:
      js-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/backend"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    groups:
      js-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/frontend"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    groups:
      js-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/frontend/qa"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    groups:
      js-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/transparent-proxy"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    groups:
      docker-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    groups:
      docker-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    groups:
      docker-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/deployment/sag"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    groups:
      docker-dependencies:
        patterns:
          - "*"
