resources:
  - ../../../base

namespace: lisa

patches:
  - path: patches/service-account.yaml
    target:
      kind: ServiceAccount
      name: lisa-sa
  - path: patches/allow-ingress-authorization-policy.yaml
    target:
      kind: AuthorizationPolicy
      name: allow-ingress-to-lisa-webapp

labels:
  - pairs:
      env: dev
      tenant: dft
images:
  - name: lisa-image:template
    newName: 537124944113.dkr.ecr.eu-west-2.amazonaws.com/lisa/webapp
    newTag: '1739959086'


