resources:
  - ../../base

namespace: lisa


configMapGenerator:
  - name: lisa-configs
    envs:
      - params.env


patches:
  - path: patches/virtualService.yaml
    target:
      kind: VirtualService
  - path: patches/service-account.yaml
    target:
      kind: ServiceAccount
      name: lisa-sa


labels:
  - pairs:
      env: demo

images:
  - name: lisa-image
    newName: 503561419905.dkr.ecr.eu-west-2.amazonaws.com/lisa/webapp
    newTag: '1739959086'


