resources:
  - ../../base

namespace: lisa-dft

patches:
  - path: patches/service-account.yaml
    target:
      kind: ServiceAccount
      name: lisa-sa
  - path: patches/allow-ingress-authorization-policy.yaml
    target:
      kind: AuthorizationPolicy
      name: allow-ingress-to-lisa-webapp

labels:
  - pairs:
      env: staging

images:
  - name: lisa-image:template
    newName: 503561419905.dkr.ecr.eu-west-2.amazonaws.com/lisa/webapp
    newTag: '1739959086'


