apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    io.kompose.service: $(TENANT)-transparent-proxy
  name: $(TENANT)-transparent-proxy
spec:
  type: ClusterIP
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: $(TENANT)-transparent-proxy
