apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: lisa-backend-vault-auth
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: lisa-backend-role
    serviceAccount: lisa-backend-sa
    audiences:
      - vault
