apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: lisa-backend-static-secret
spec:
  refreshAfter: 30s
  # path of the secret
  path: applications/lisa/backend
  type: kv-v2
  mount: k8-cluster
  destination:
    # destination k8s secret
    name: lisa-backend-secrets
    create: true
  vaultAuthRef: lisa-backend-vault-auth
