apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: $(TENANT)-backend-vault-auth
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: $(TENANT)-backend-role
    serviceAccount: $(TENANT)-backend-sa
    audiences:
      - vault
