resources:
  - ../../base

namespace: lisa

configMapGenerator:
  - name: lisa-transparent-proxy-configs
    envs:
      - params.env

patches:

  - path: patches/service-account.yaml
    target:
      kind: ServiceAccount

labels:
  - pairs:
      env: prod

images:
  - name: lisa-transparent-proxy-image:template
    newName: 940482405940.dkr.ecr.eu-west-2.amazonaws.com/lisa/transparent-proxy
    newTag: "1736292556"


