
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-ingress-to-lisa-webapp
spec:
  selector:
    matchLabels:
      tenant: dft
  action: ALLOW
  rules:

     - when:
       - key: request.auth.claims[groups]
         values:
             - lisa_dft_access