apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: $(TENANT)-transparent-proxy-vault-auth
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: $(TENANT)-transparent-proxy-role
    serviceAccount: $(TENANT)-transparent-proxy-sa
    audiences:
      - vault
