
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-ingress-to-$(TENANT)-backend
spec:
  selector:
    matchLabels:
      io.kompose.service: $(TENANT)-backend
  action: ALLOW
  rules:
    - from:
        - source:
            principals : ["PLACE_HOLDER"]
      to:
        - operation:
            methods: ["GET","POST","PUT"]
      when:
        - key: request.auth.claims[groups]
          values:
            - lisa_access