
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-ingress-to-lisa-backend
spec:
  selector:
    matchLabels:
      io.kompose.service: lisa-backend
  action: ALLOW
  rules:
    - from:
        - source:
            principals : ["cluster.local/ns/istio-ingress/sa/istio-ingress"]
      to:
        - operation:
            methods: ["GET","PATCH", "POST","PUT"]
      when:
        - key: request.auth.claims[groups]
          values:
            - lisa_access