apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: lisa
spec:
  hosts:
    - lisa.demo.ndtp.co.uk
  gateways:
    - lisa/lisa-ingress-gateway
  http:
    - match:
        - uri:
            prefix: /
      rewrite:
        uriRegexRewrite:
          match: ^/(/|$)(.*)
          rewrite: /\2
      route:
        - destination:
            host: lisa
            port:
              number: 80
          headers:
            response:
              set:
                Content-Security-Policy: >-
                  connect-src 'self' data: wss://lisa.demo.ndtp.co.uk ws://lisa.demo.ndtp.co.uk https://lisa.demo.ndtp.co.uk https://api.os.uk https://nominatim.openstreetmap.org;
                  worker-src 'self' blob:;
                  child-src 'self' blob:;
                  img-src 'self' data: blob:
