apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  name: lisa-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: lisa
  template:
    metadata:
      annotations: {}
      labels:
        io.kompose.service: lisa
    spec:
      serviceAccountName: lisa-sa
      containers:
        - image: lisa-image
          livenessProbe:
            httpGet:
              path: /
              port: 80
            failureThreshold: 5
            periodSeconds: 30
            timeoutSeconds: 20
          readinessProbe:
              httpGet:
                path: /
                port: 80
              failureThreshold: 5
              periodSeconds: 30
              timeoutSeconds: 20
          name: lisa
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always