apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  name: $(TENANT)-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: $(TENANT)
  template:
    metadata:
      annotations: {}
      labels:
        io.kompose.service: $(TENANT)
    spec:
      serviceAccountName: $(TENANT)-sa
      containers:
        - image: lisa-image:template
          livenessProbe:
            httpGet:
              path: /
              port: 80
            failureThreshold: 5
            periodSeconds: 30
            timeoutSeconds: 20
          readinessProbe:
              httpGet:
                path: /
                port: 80
              failureThreshold: 5
              periodSeconds: 30
              timeoutSeconds: 20
          name: $(TENANT)
          resources:
            limits:
              memory: "2Gi"
            requests:
              cpu: "0.25"
              memory: "256Mi"
              ephemeral-storage: "2Gi"
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always