apiVersion: v1
kind: Service
metadata:
  annotations: {}

  labels:
    io.kompose.service: $(TENANT)
  name: $(TENANT)
spec:
  type: NodePort
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: $(TENANT)