apiVersion: v1
kind: Service
metadata:
  annotations: {}

  labels:
    io.kompose.service: lisa
  name: lisa
spec:
  type: NodePort
  ports:
    - name: "80"
      port: 80
      targetPort: 8080
  selector:
    io.kompose.service: lisa