
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-ingress-to-transparent-proxy
spec:
  selector:
    matchLabels:
      io.kompose.service: $(TENANT)-transparent-proxy
  action: ALLOW
  rules:
    - from:
        - source:
            principals: ["cluster.local/ns/istio-ingress/sa/istio-ingress"]
      to:
        - operation:
            methods: ["GET","POST"]
      when:
        - key: request.auth.claims[groups]
          values:
            - lisa_access