version: '3'
services:
  zookeeper:
    container_name: lisa-zookeeper
    image: bitnami/zookeeper:latest
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    container_name: lisa-kafka
    depends_on:
      - zookeeper
    image: 'bitnami/kafka:3.5'
    ports:
      - '9092:9092'
    volumes:
      - ./kafka/server.properties:/bitnami/kafka/config/server.properties
    environment:
      - BITNAMI_DEBUG=true
  secure-agent-graph:
    container_name: lisa-sag
    depends_on:
      - zookeeper
      - kafka
    environment:
      JAVA_OPTIONS: '-XX:MaxRAMPercentage=40.0'
      JWKS_URL: 'disabled'
    command:
      - --config
      - /fuseki/config/config.ttl
    image: lisa/secure-agent-graph
    ports:
      - 3030:3030
  transparent-proxy:
    container_name: lisa-transparent-proxy
    environment:
      OS_RASTER_API_KEY: 'REPLACE ME'
    image: lisa/transparent-proxy
    ports:
      - 8000:80
