
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-ingress-to-lisa-webapp
spec:
  selector:
    matchLabels:
      io.kompose.service: lisa
  action: ALLOW
  rules:
    - from:
        - source:
            principals : ["PLACE_HOLDER"]
      to:
        - operation:
            methods: ["GET","POST","PUT"]
