apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: lisa
spec:
  hosts:
    - placeholder
  gateways:
    - placeholder
  http:
    - match:
        - uri:
            exact: /
      headers:
        response:
          add:
            Cache-Control: "no-cache, no-store, must-revalidate"
            Pragma: "no-cache"
            Expires: "0"
      route:
        - destination:
            host: lisa
            port:
              number: 80

    - match:
        - uri:
            prefix: /
      rewrite:
        uriRegexRewrite:
          match: ^/(/|$)(.*)
          rewrite: /\2

      route:
        - destination:
            host: lisa
            port:
              number: 80
