apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: lisa
spec:
  hosts:
    - placeholder
  gateways:
    - placeholder
  http:
    # Rule for root ("/") and "/index.html" to prevent caching
    - match:
        - uri:
            exact: /
        - uri:
            exact: /index.html
      headers:
        response:
          add:
            Cache-Control: "no-cache, no-store, must-revalidate"
            Pragma: "no-cache"
            Expires: "0"
      route:
        - destination:
            host: lisa
            port:
              number: 80

    - match:
        - uri:
            prefix: /
      rewrite:
        uriRegexRewrite:
          match: ^/(/|$)(.*)
          rewrite: /\2

      route:
        - destination:
            host: lisa
            port:
              number: 80
          headers:
            response:
              set:
                Content-Security-Policy: >-
                  connect-src 'self' data: wss://lisa.demo.ndtp.co.uk ws://lisa.demo.ndtp.co.uk https://lisa.demo.ndtp.co.uk https://api.os.uk https://nominatim.openstreetmap.org;
                  worker-src 'self' blob:;
                  child-src 'self' blob:;
                  img-src 'self' data: blob:
