# SPDX-License-Identifier: Apache-2.0
# © Crown Copyright 2025. This work has been developed by the National Digital Twin Programme and is legally attributed to the Department for Business and Trade (UK) as the governing entity.

name: Frontend CI on PR

on:
  workflow_call:
  pull_request:
    branches:
      - 'develop'
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci-pr.yml'
      - '.github/workflows/frontend-ci-pr-merge.yml'
  workflow_dispatch:

permissions:
  contents: read
  packages: read
  statuses: write # To report GitHub Actions status checks

jobs:
  dependencies:
    name: Dependency Checks
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'

      - name: Install Dependencies
        run: npm ci

      - name: Check for Outdated Dependencies
        run: npm audit
        continue-on-error: true

  linting:
    name: Code Linting
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: dependencies
    env:
      GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'

      - name: Install Dependencies
        run: npm ci

      - name: Run Linting
        working-directory: frontend
        run: npm run lint
        continue-on-error: true

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: dependencies
    env:
      GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TZ: UTC
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'

      - name: Install Dependencies
        run: npm ci

      - name: Run Frontend Tests
        working-directory: frontend
        run: |
          npm run test

      - name: Run Common Unit Tests
        working-directory: common
        run: |
          npm run test

  security-scanning:
    name: Security Scanning
    runs-on: ubuntu-latest
    needs: linting
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.32.0
        with:
          scan-type: 'fs'
          scan-ref: frontend
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

  docker-build-test-scan:
    name: Build, Docker Build, Test & Scan
    runs-on: ubuntu-latest
    needs: security-scanning
    timeout-minutes: 20
    env:
      GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    environment: development
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'

      - name: Install Dependencies
        run: npm ci

      - name: Build Frontend
        run: |
          (cd ./frontend && npm run build)
          (cd ./frontend && npm run bundle)

      - name: List files in dist dir
        if: success()
        working-directory: frontend
        run: |
          ls -l dist

      - name: Build Docker Image
        run: |
          docker build -t lisa/webapp:latest -f Dockerfile.frontend .

      - name: Run Trivy Scan on Docker Image
        uses: aquasecurity/trivy-action@0.32.0
        with:
          image-ref: 'lisa/webapp:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          trivyignores: 'frontend/.trivyignore'
