# SPDX-License-Identifier: Apache-2.0
# © Crown Copyright 2025. This work has been developed by the National Digital Twin Programme and is legally attributed to the Department for Business and Trade (UK) as the governing entity.

name: Release on New Release Branch

on:
  push:
    branches:
      - "release/*"

env:
  VERSION: ${{ replace(replace(github.ref_name, 'release/', ''), '-', '.') }}

permissions:
  id-token: write
  contents: write
  packages: read
  statuses: write

jobs:
  backend-ci:
    uses: ./.github/workflows/backend-ci-pr.yml

  frontend-ci:
    uses: ./.github/workflows/frontend-ci-pr.yml

  proxy-ci:
    uses: ./.github/workflows/transparent-proxy-ci-pr.yml

  backend-push-to-ECR:
    needs: [backend-ci]
    uses: ./.github/workflows/backend-cd-push-to-ECR.yml
    with:
      aws_account_number: "${{ vars.STAGING_AWS_ACCOUNT_ID }}"
      repo_name: "lisa/api"
      app_name: "lisa/api"
      version: ${{ env.VERSION }}

  frontend-push-to-ECR:
    needs: [frontend-ci]
    uses: ./.github/workflows/frontend-cd-push-to-ECR.yml
    with:
      aws_account_number: "${{ vars.STAGING_AWS_ACCOUNT_ID }}"
      repo_name: "lisa/webapp"
      app_name: "lisa/webapp"
      version: ${{ env.VERSION }}

  proxy-push-to-ECR:
    needs: [proxy-ci]
    uses: ./.github/workflows/transparent-proxy-cd-push-to-ECR.yml
    with:
      aws_account_number: "${{ vars.STAGING_AWS_ACCOUNT_ID }}"
      repo_name: "lisa/transparent-proxy"
      app_name: "transparent-proxy"
      version: ${{ env.VERSION }}